### ISSUE TITLE
Only shows extra data if I scan all files in SlicerSettingsParser

### ISSUE THREAD

**Issue by Alf-Tupper** [larsjuhw/OctoPrint-ExtraFileInfo#21] opened 2024-10-21 16:18 UTC
I have seen the known issue with newly uploaded files when using Cura Thumbnails, so I deleted this and I'm now using Slicer Thumbnails, but I still don't get the extra data for newly uploaded files unless I scan all files.

Please can you help.

Cheers, Dean

**Comment by larsjuhw** [comment] 2024-10-21 17:19
Could you provide some logs, a list of installed plugins, and your OctoPrint version?

**Comment by Alf-Tupper** [comment] 2024-10-21 17:41
Please find the details requested below and I have attach a couple of logs. 

OctoPrint: 1.10.2 

  | Achievements Plugin 
  | Action Command Notification Support 
  | Action Command Prompt Support  
  | Active Filters Extended (0.1.0) 
  | Announcement Plugin 
  | Anonymous Usage Tracking  
  | Application Keys Plugin   
  | Arc-Welder (1.0.0+u.bb71e8f) 
  | Autoscroll (0.0.3) 
  | Backup & Restore   
  | Bed Visualizer (1.1.1) 
  | Cancel Objects (0.5.0) 
  | Classic Webcam 
  | Consolidate Temp Control (0.1.10)
  | Consolidated Tabs (1.0.2)
  | Core Wizard
  | Cost Estimation (3.5.0)
  | Dashboard (1.19.12) 
  | Discovery   Homepage 
  | DisplayLayerProgress Plugin (1.28.0) 
  | Error Tracking   
  | Event Manager
  | Exclude Region (0.3.2) 
  | ExtraFileInfo (1.4.0) 
  | File Check (2024.3.27)  
  | Firmware Check (2021.10.11)  
  | Firmware Updater (1.14.1)
  | GCode Viewer 
  | HeaterTimeout (0.0.4) 
  | Logging  
  | Macro (0.3.2) 
  | Octolapse (0.4.5) 
  | Power Failure Recovery (1.2.1) 
  | Preheat Button (0.8.0)
  | PrettyGCode (1.2.4)
  | PrintJobHistory (1.17.2) 
  | PrintTimeGenius Plugin (2.3.3) 
  | Resource Monitor (0.3.16)
  | Simple Emergency Stop (1.0.6) 
  | Slicer Thumbnails (1.0.7) 
  | SlicerSettingsParser (3.3.0) 
  | Software Update   
  | SpoolManager Plugin (1.7.4) 
  | Terminal Commands Extended (0.1.7) 
  | UI Customizer (0.1.9.91) 
  | Virtual Printer 

[octoprint.log](https://github.com/user-attachments/files/17464960/octoprint.log)
[plugin_pluginmanager_console.log](https://github.com/user-attachments/files/17464961/plugin_pluginmanager_console.log)

**Comment by larsjuhw** [comment] 2024-10-22 10:34
I'm currently busy with exams so I'll check it out when I have some time.

**Comment by larsjuhw** [comment] 2024-10-26 14:12
I see that you have Arc-Welder installed. Do you have "Overwrite Source File" enabled in its settings? SlicerSettingsParser only analyzes on file upload, so when Arc-Welder replaces the original file, the parsing likely isn't getting triggered.

**Comment by Rednax74** [comment] 2024-11-06 10:17
Hello, I have the same issue and I also just noticed that this is caused by Arc-Welder, after inital upload the data is there, but after arkwelder processed the file no additional info is there. 
I am not overwriting the original file, I generate a new one with .aw extension (and the original file is deleted). But also in this case the extrafile info parsing is not triggered. So maybe you could also trigger the parsing if a new file is creasted (maybe this is a different event than an upload).

**Comment by Alf-Tupper** [comment] 2024-11-06 11:17
Sorry I've not replied sooner, had totally forgot! Yes, I have the "Overwrite Source File" enabled. Is there a way around this?

**Comment by larsjuhw** [comment] 2024-11-06 14:06
Might be fixable depending on how Arc-Welder does the processing. I'll look into it somewhere next week.

**Comment by larsjuhw** [comment] 2024-11-25 22:27
@Alf-Tupper I've released an RC version 3.3.1rc1 for SlicerSettingsParser that seems to resolve the issue. You can test it by setting the release channel of SlicerSettingsParser to Release Candidate in the Software Update settings of OctoPrint, or by manually installing this URL in the plugin manager: https://github.com/larsjuhw/OctoPrint-SlicerSettingsParser/archive/refs/tags/v3.3.1rc1.zip

Let me know if this solves your issue! Haven't been able to properly test if this introduces any new conflicts though.

**Comment by Rednax74** [comment] 2024-11-27 20:33
ok I just installed it and now the info is displayed even after arc welder processed it! I'll check against any negative sideeffects...

**Comment by larsjuhw** [comment] 2024-11-29 11:40
Great! I'm closing this issue, let me know if there are any side effects.

**Closed as completed by larsjuhw** 2024-11-29 11:40 UTC
